# docker-compose.override.yml
services:
  signaling:
    build:
      context: ./signaling
    environment:
      - APP_ORIGIN=https://dev.call.navi.jpn.com
      - KURENTO_URI=ws://neoria.fun:8888/kurento
      - NODE_ENV=production
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - sail

networks:
  sail:
    driver: bridge

